[build]
  base = "/"
  publish = "public"
  command = "npm run build"

[context.production]
  command = "npm run build && npm run ipfs-deploy"

[build.environment]
  HUGO_VERSION = "0.69.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[[redirects]]
  from = "https://ruchan.netlify.com/*"
  to = "https://crcrc.me/:splat"
  status = 301
  force = true
  
  