[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  HUGO_VERSION = "0.68.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.production]
  command = "npm run build"
  
[[redirects]]
  from = "https://ruchan.netlify.com/*"
  to = "https://crcrc.me/:splat"
  force = true
  
  